language: ruby
rvm:
  - 2.1.0
  - 2.1.1
  - 2.1.2

gemfile:
  - Gemfile

env:
  - DB=mysql

before_script:
  - mysql -e 'create database `goal-rails_test`;'

#script:
  #- RAILS_ENV=test bundle exec rake --trace db:migrate
  #- bundle exec rake db:test:prepare
