language: ruby
rvm:
  - 2.1

gemfile:
  - Gemfile

env:
  - DB=mysql    DATABASE_ADAPTER=mysql2
  - DB=postgres DATABASE_ADAPTER=postgresql
  - DB=sqlite3  DATABASE_ADAPTER=sqlite3

bundler_args: --without development --path=vendor/bundle --binstubs=vendor/bin

cache:
  directories:
    - vendor/bundle
    - vendor/bin

before_script:
  - sh -c 'if [ $DB = "mysql" ];    then mysql -e "create database goal_rails_test";           fi'
  - sh -c 'if [ $DB = "postgres" ]; then psql  -c "create database goal_rails_test" -U travis; fi'

#script:
  #- RAILS_ENV=test bundle exec rake --trace db:migrate
  #- bundle exec rake db:test:prepare
